n_melee=argument0.n_melee;
n_ranged_gun=argument0.n_ranged_gun;
n_ranged_machinegun=argument0.n_ranged_machinegun;
n_ranged_shotgun=argument0.n_ranged_shotgun;
n_ranged_magnum=argument0.n_ranged_magnum;
cooldown_melee_frames=argument0.cooldown_melee_frames;
cooldown_gun_frames=argument0.cooldown_gun_frames;
cooldown_machinegun_frames=argument0.cooldown_machinegun_frames;
cooldown_shotgun_frames=argument0.cooldown_shotgun_frames;
cooldown_magnum_frames=argument0.cooldown_magnum_frames;
	